version: '3.3'
services:
    test:
        network_mode: host
        image: robot
        shm_size: "256M"
        environment:
            USERNAME: cuong.buiviet
        volumes: [
           "$PWD/testcases:/testcases",
           "$PWD/scripts:/scripts",
           "$PWD/keywords:/keywords",
           "$PWD/resources:/resources",
           "$PWD/common:/common",
           "$PWD/reports:/reports"
        ]